-- This file will contain all the table creation scripts.
DROP TABLE users;
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('admin', 'pm', 'client', 'developer', 'sales')),
    email VARCHAR2(255) NOT NULL UNIQUE,
    name VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    is_active NUMBER(1,0) DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1))
);

-- Optional: Add comments for better documentation
COMMENT ON TABLE users IS 'Stores user information for the application.';
COMMENT ON COLUMN users.user_id IS 'Unique identifier for the user.';
COMMENT ON COLUMN users.role IS 'Role of the user (admin, pm, client, developer, sales).';
COMMENT ON COLUMN users.email IS 'Unique email address of the user.';
COMMENT ON COLUMN users.password IS 'password of the user.';
COMMENT ON COLUMN users.is_active IS 'Status of the user (1 for active, 0 for inactive).';